### ISSUE TITLE
Custom download/model folder?

### ISSUE THREAD

**Issue by Selur** [TensoRaws/ccrestoration#16]
Not sure whether I am missing something or if there is a bug. :)
(I'm on Windows 11 using portable Vapoursynth R70)
I installed ccrestoration using:
```
F:\Hybrid\64bit\Vapoursynth>python -m pip install ccrestoration
Collecting ccrestoration
  Downloading ccrestoration-0.0.11-py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: einops in f:\hybrid\64bit\vapoursynth\lib\site-packages (from ccrestoration) (0.8.0)
Requirement already satisfied: opencv-python in f:\hybrid\64bit\vapoursynth\lib\site-packages (from ccrestoration) (4.10.0.84)
Requirement already satisfied: pydantic in f:\hybrid\64bit\vapoursynth\lib\site-packages (from ccrestoration) (2.9.2)
Collecting tenacity (from ccrestoration)
  Downloading tenacity-9.0.0-py3-none-any.whl.metadata (1.2 kB)
Requirement already satisfied: numpy>=1.21.2 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from opencv-python->ccrestoration) (1.26.4)
Requirement already satisfied: annotated-types>=0.6.0 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from pydantic->ccrestoration) (0.7.0)
Requirement already satisfied: pydantic-core==2.23.4 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from pydantic->ccrestoration) (2.23.4)
Requirement already satisfied: typing-extensions>=4.6.1 in f:\hybrid\64bit\vapoursynth\lib\site-packages (from pydantic->ccrestoration) (4.12.2)
Downloading ccrestoration-0.0.11-py3-none-any.whl (72 kB)
Downloading tenacity-9.0.0-py3-none-any.whl (28 kB)
Installing collected packages: tenacity, ccrestoration
Successfully installed ccrestoration-0.0.11 tenacity-9.0.0
```
which seems to work fine.
Then I created toe following Vapoursynth scipt:
```
# Imports
import vapoursynth as vs
# getting Vapoursynth core
import sys
import os
core = vs.core
# Import scripts folder
scriptPath = 'F:/Hybrid/64bit/vsscripts'
sys.path.insert(0, os.path.abspath(scriptPath))
# loading plugins
core.std.LoadPlugin(path="F:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/LSMASHSource.dll")
# Import scripts
import validate
# Source: 'G:\TestClips&Co\files\test.avi'
# Current color space: YUV420P8, bit depth: 8, resolution: 640x352, frame rate: 25fps, scanorder: progressive, yuv luminance scale: limited, matrix: 470bg, format: MPEG-4 Visual
# Loading G:\TestClips&Co\files\test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="G:/TestClips&Co/files/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)
frame = clip.get_frame(0)
# setting color matrix to 470bg.
clip = core.std.SetFrameProps(clip, _Matrix=vs.MATRIX_BT470_BG)
# setting color transfer (vs.TRANSFER_BT601), if it is not set.
if validate.transferIsInvalid(clip):
  clip = core.std.SetFrameProps(clip=clip, _Transfer=vs.TRANSFER_BT601)
# setting color primaries info (to vs.PRIMARIES_BT470_BG), if it is not set.
if validate.primariesIsInvalid(clip):
  clip = core.std.SetFrameProps(clip=clip, _Primaries=vs.PRIMARIES_BT470_BG)
# setting color range to TV (limited) range.
clip = core.std.SetFrameProps(clip=clip, _ColorRange=vs.RANGE_LIMITED)
# making sure frame rate is set to 25fps
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# making sure the detected scan type is set (detected: progressive)
clip = core.std.SetFrameProps(clip=clip, _FieldBased=vs.FIELD_PROGRESSIVE) # progressive
# adjusting color space from YUV420P8 to RGBH for ccrestoration
clip = core.resize.Bicubic(clip=clip, format=vs.RGBH, matrix_in_s="470bg", range_s="limited")
# Quality enhancement using ccrestoration

from ccrestoration import AutoModel, BaseModelInterface, ConfigType

ccRestorationModel: BaseModelInterface = AutoModel.from_pretrained(
    pretrained_model_name=ConfigType.AnimeSR_v2_4x
)

clip = ccRestorationModel.inference_video(clip)

# adjusting output color from: RGBH to YUV420P10 for NVEncModel
clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P10, matrix_s="470bg", range_s="limited", dither_type="error_diffusion")
# set output frame rate to 25fps (progressive)
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# output
clip.set_output()
```
but this gives me:
```
2024-10-13 08:55:46.406 Failed to evaluate the script:Python exception: RetryError[]Traceback (most recent call last):File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 478, in __call__result = fn(*args, **kwargs)^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 54, in _downloadraise eFile "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 51, in _downloaddownload_url_to_file(str(config.url), cached_file_path, hash_prefix=None, progress=progress)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\hub.py", line 736, in download_url_to_filewith tqdm(^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1098, in __init__self.refresh(lock_args=self.lock_args)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1347, in refreshself.display()File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1495, in displayself.sp(self.__str__() if msg is None else msg)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 459, in print_statusfp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 452, in fp_writefp.write(str(s))^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\utils.py", line 140, in __getattr__return getattr(self._wrapped, name)^^^^^^^^^^^^^^^^^^^^^^^^^^^^AttributeError: 'NoneType' object has no attribute 'write'The above exception was the direct cause of the following exception:Traceback (most recent call last):File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\sr_base_model.py", line 26, in get_state_dictmodel_path = load_file_from_url(cfg)^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 56, in load_file_from_url_download()File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 336, in wrapped_freturn copy(f, *args, **kw)^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 475, in __call__do = self.iter(retry_state=retry_state)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 376, in iterresult = action(retry_state)^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 419, in exc_checkraise retry_exc from fut.exception()tenacity.RetryError: RetryError[]During handling of the above exception, another exception occurred:Traceback (most recent call last):File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 478, in __call__result = fn(*args, **kwargs)^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 54, in _downloadraise eFile "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 51, in _downloaddownload_url_to_file(str(config.url), cached_file_path, hash_prefix=None, progress=progress)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\hub.py", line 736, in download_url_to_filewith tqdm(^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1098, in __init__self.refresh(lock_args=self.lock_args)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1347, in refreshself.display()File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1494, in displayself.moveto(pos)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1443, in movetoself.fp.write('\n' * n + _term_move_up() * -n)^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\utils.py", line 140, in __getattr__return getattr(self._wrapped, name)^^^^^^^^^^^^^^^^^^^^^^^^^^^^AttributeError: 'NoneType' object has no attribute 'write'The above exception was the direct cause of the following exception:Traceback (most recent call last):File "src\\cython\\vapoursynth.pyx", line 3387, in vapoursynth._vpy_evaluateFile "src\\cython\\vapoursynth.pyx", line 3388, in vapoursynth._vpy_evaluateFile "C:\Users\Selur\Desktop\Vapoursynth Scripts\test.vpy", line 39, in ccRestorationModel: BaseModelInterface = AutoModel.from_pretrained(^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\auto\model.py", line 37, in from_pretrainedreturn AutoModel.from_config(^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\auto\model.py", line 74, in from_configmodel = model(^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\type\base_model.py", line 51, in __init__self.model: torch.nn.Module = self.load_model()^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\animesr_model.py", line 14, in load_modelstate_dict = self.get_state_dict()^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\sr_base_model.py", line 29, in get_state_dictmodel_path = load_file_from_url(cfg, force_download=True)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 56, in load_file_from_url_download()File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 336, in wrapped_freturn copy(f, *args, **kw)^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 475, in __call__do = self.iter(retry_state=retry_state)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 376, in iterresult = action(retry_state)^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 419, in exc_checkraise retry_exc from fut.exception()tenacity.RetryError: RetryError[]
--
2024-10-13 08:58:27.364 Failed to evaluate the script:Python exception: RetryError[]Traceback (most recent call last):File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 478, in __call__result = fn(*args, **kwargs)^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 54, in _downloadraise eFile "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 51, in _downloaddownload_url_to_file(str(config.url), cached_file_path, hash_prefix=None, progress=progress)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\hub.py", line 736, in download_url_to_filewith tqdm(^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1098, in __init__self.refresh(lock_args=self.lock_args)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1347, in refreshself.display()File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1495, in displayself.sp(self.__str__() if msg is None else msg)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 459, in print_statusfp_write('\r' + s + (' ' * max(last_len[0] - len_s, 0)))File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 452, in fp_writefp.write(str(s))^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\utils.py", line 140, in __getattr__return getattr(self._wrapped, name)^^^^^^^^^^^^^^^^^^^^^^^^^^^^AttributeError: 'NoneType' object has no attribute 'write'The above exception was the direct cause of the following exception:Traceback (most recent call last):File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\sr_base_model.py", line 26, in get_state_dictmodel_path = load_file_from_url(cfg)^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 56, in load_file_from_url_download()File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 336, in wrapped_freturn copy(f, *args, **kw)^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 475, in __call__do = self.iter(retry_state=retry_state)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 376, in iterresult = action(retry_state)^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 419, in exc_checkraise retry_exc from fut.exception()tenacity.RetryError: RetryError[]During handling of the above exception, another exception occurred:Traceback (most recent call last):File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 478, in __call__result = fn(*args, **kwargs)^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 54, in _downloadraise eFile "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 51, in _downloaddownload_url_to_file(str(config.url), cached_file_path, hash_prefix=None, progress=progress)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\hub.py", line 736, in download_url_to_filewith tqdm(^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1098, in __init__self.refresh(lock_args=self.lock_args)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1347, in refreshself.display()File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1494, in displayself.moveto(pos)File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\std.py", line 1443, in movetoself.fp.write('\n' * n + _term_move_up() * -n)^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tqdm\utils.py", line 140, in __getattr__return getattr(self._wrapped, name)^^^^^^^^^^^^^^^^^^^^^^^^^^^^AttributeError: 'NoneType' object has no attribute 'write'The above exception was the direct cause of the following exception:Traceback (most recent call last):File "src\\cython\\vapoursynth.pyx", line 3387, in vapoursynth._vpy_evaluateFile "src\\cython\\vapoursynth.pyx", line 3388, in vapoursynth._vpy_evaluateFile "C:\Users\Selur\Desktop\Vapoursynth Scripts\test.vpy", line 39, in ccRestorationModel: BaseModelInterface = AutoModel.from_pretrained(^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\auto\model.py", line 37, in from_pretrainedreturn AutoModel.from_config(^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\auto\model.py", line 74, in from_configmodel = model(^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\type\base_model.py", line 51, in __init__self.model: torch.nn.Module = self.load_model()^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\animesr_model.py", line 14, in load_modelstate_dict = self.get_state_dict()^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\sr_base_model.py", line 29, in get_state_dictmodel_path = load_file_from_url(cfg, force_download=True)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\__init__.py", line 56, in load_file_from_url_download()File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 336, in wrapped_freturn copy(f, *args, **kw)^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 475, in __call__do = self.iter(retry_state=retry_state)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 376, in iterresult = action(retry_state)^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\tenacity\__init__.py", line 419, in exc_checkraise retry_exc from fut.exception()tenacity.RetryError: RetryError[]
```
when trying to preview the script in vsViewer.
When using: 
`vspipe "c:\Users\Selur\Desktop\Vapoursynth Scripts\test.vpy" -c y4m NUL`
the file is downloaded and processed properly:
```F:\Hybrid\64bit\Vapoursynth>vspipe "c:\Users\Selur\Desktop\Vapoursynth Scripts\test.vpy" -c y4m NUL
Downloading: https://github.com/TensoRaws/ccrestoration/releases/download/model_zoo/AnimeSR_v2_4x.pth to F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\AnimeSR_v2_4x.pth

100%|█████████████████████████████████████████████████████████████████████████████| 5.72M/5.72M [00:00<00:00, 12.3MB/s]
Warning: F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\vs\convert.py:8: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:212.)
  [torch.from_numpy(np.asarray(frame[plane])).to(device) for plane in range(frame.format.num_planes)]
```
Would it be possible to add an option to allow a custom download/model folder, so I can download the model from the release beforehand and tell ccrestoration where to find them?
(since I try to keep things portable not needing to download stuff each time or having to trigger vspipe for the download would help)

Thanks for considering this.

**Comment by Tohrusky** [comment]
as you can see `F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\cache_models\` is your cache model's folder, you can download model [here](https://github.com/TensoRaws/ccrestoration/releases/tag/model_zoo)
*And We will add an option to support custom folder*

By the way, we use yuuno to preview, it can auto download model, here's the playground project https://github.com/TensoRaws/vs-playground

**Comment by Tohrusky** [comment]
done in https://github.com/TensoRaws/ccrestoration/pull/17
v0.0.12 has been released

**Comment by Selur** [comment]
Works fine, thanks!
