### ISSUE TITLE
Problem using some of the models

### ISSUE THREAD

**Issue by Selur** [TensoRaws/ccrestoration#18]
Trying some of the pretrained models, using the following script:
```
# Imports
import vapoursynth as vs
# getting Vapoursynth core
import sys
import os
core = vs.core
# Import scripts folder
scriptPath = 'F:/Hybrid/64bit/vsscripts'
sys.path.insert(0, os.path.abspath(scriptPath))
# loading plugins
core.std.LoadPlugin(path="F:/Hybrid/64bit/vsfilters/SourceFilter/LSmashSource/LSMASHSource.dll")
# Import scripts
import validate
# Source: 'G:\TestClips&Co\files\test.avi'
# Current color space: YUV420P8, bit depth: 8, resolution: 640x352, frame rate: 25fps, scanorder: progressive, yuv luminance scale: limited, matrix: 470bg, format: MPEG-4 Visual
# Loading G:\TestClips&Co\files\test.avi using LWLibavSource
clip = core.lsmas.LWLibavSource(source="G:/TestClips&Co/files/test.avi", format="YUV420P8", stream_index=0, cache=0, prefer_hw=0)
frame = clip.get_frame(0)
# setting color matrix to 470bg.
clip = core.std.SetFrameProps(clip, _Matrix=vs.MATRIX_BT470_BG)
# setting color transfer (vs.TRANSFER_BT601), if it is not set.
if validate.transferIsInvalid(clip):
  clip = core.std.SetFrameProps(clip=clip, _Transfer=vs.TRANSFER_BT601)
# setting color primaries info (to vs.PRIMARIES_BT470_BG), if it is not set.
if validate.primariesIsInvalid(clip):
  clip = core.std.SetFrameProps(clip=clip, _Primaries=vs.PRIMARIES_BT470_BG)
# setting color range to TV (limited) range.
clip = core.std.SetFrameProps(clip=clip, _ColorRange=vs.RANGE_LIMITED)
# making sure frame rate is set to 25fps
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# making sure the detected scan type is set (detected: progressive)
clip = core.std.SetFrameProps(clip=clip, _FieldBased=vs.FIELD_PROGRESSIVE) # progressive
# adjusting color space from YUV420P8 to RGBH for ccrestoration
clip = core.resize.Bicubic(clip=clip, format=vs.RGBH, matrix_in_s="470bg", range_s="limited")
org = clip

# Quality enhancement using ccrestoration
from ccrestoration import AutoModel, BaseModelInterface, ConfigType

ccRestorationModel: BaseModelInterface = AutoModel.from_pretrained(
    pretrained_model_name=ConfigType.SwinIR_classicalSR_DF2K_s64w8_SwinIR_M_2x,
    model_dir = 'f:/Hybrid/64bit/ccrestoration_models'
)
clip = ccRestorationModel.inference_video(clip)


clip = core.resize.Bicubic(clip=clip, format=vs.RGBS)
org = core.resize.Bicubic(clip=org, format=vs.RGBS, width=clip.width, height=clip.height)
clip = core.std.Interleave([org.text.Text("Original"), clip.text.Text("Filtered")])

# adjusting output color from: RGBH to YUV420P10 for NVEncModel
clip = core.resize.Bicubic(clip=clip, format=vs.YUV420P10, matrix_s="470bg", range_s="limited", dither_type="error_diffusion")
# set output frame rate to 25fps (progressive)
clip = core.std.AssumeFPS(clip=clip, fpsnum=25, fpsden=1)
# output
clip.set_output()
```

I get:
```
2024-10-14 19:09:34.173 Error on frame 1 request:Traceback (most recent call last):File "src\\cython\\vapoursynth.pyx", line 3216, in vapoursynth.publicFunctionFile "src\\cython\\vapoursynth.pyx", line 3218, in vapoursynth.publicFunctionFile "src\\cython\\vapoursynth.pyx", line 834, in vapoursynth.FuncData.__call__File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\vs\sr.py", line 35, in _inferenceoutput = inference(img)^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_contextreturn func(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\sr_base_model.py", line 45, in inferencereturn tile_sr(^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\tile.py", line 84, in tile_sroutput_tile = model(input_tile)^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_implreturn self._call_impl(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_implreturn forward_call(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\swinir_arch.py", line 250, in forwardx = self.conv_after_body(self.forward_features(x)) + x^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\swinir_arch.py", line 233, in forward_featuresx = layer(x, x_size)^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_implreturn self._call_impl(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_implreturn forward_call(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\swinir_arch.py", line 828, in forwardreturn self.patch_embed(self.conv(self.patch_unembed(self.residual_group(x, x_size), x_size))) + x^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_implreturn self._call_impl(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_implreturn forward_call(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\swinir_arch.py", line 725, in forwardx = blk(x, x_size)^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_implreturn self._call_impl(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_implreturn forward_call(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\swinir_arch.py", line 561, in forwardattn_windows = self.attn(x_windows, mask=self.calculate_mask(x_size).to(x.device))^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_implreturn self._call_impl(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_implreturn forward_call(*args, **kwargs)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\swinir_arch.py", line 418, in forwardx = (attn @ v).transpose(1, 2).reshape(B_, N, C)~~~~~^~~RuntimeError: expected scalar type Half but found Float
```
Using the above code and only changing the 'pretrained_model_name':

Group models that work:
* AnimeSR
* EDSR
* RealCUGAN
* RealESRGAN
* SCUNet
* EDVR
Group models that fail:
* BasicVSR
* IconVSR
* SwinIR
SpyNet_spynet_sintel_final and the EDVRFeatureExtractor models give me: "Auxiliary model has no inference_video method"

Any idea what I'm missing?

**Comment by Tohrusky** [comment]
auxiliary model is used in the other network, work as a module, like spynet is a flownet and edvrfe is just a feature extractor.

Try use `fp16=False`  if you got `RuntimeError: expected scalar type Half but found Float` see https://github.com/TensoRaws/ccrestoration/blob/main/example/vapoursynth.py

**Comment by Selur** [comment]
using:
```
# adjusting color space from YUV420P8 to RGBH for ccrestoration
clip = core.resize.Bicubic(clip=clip, format=vs.RGBH, matrix_in_s="470bg", range_s="limited")
org = clip

# Quality enhancement using ccrestoration
from ccrestoration import AutoModel, BaseModelInterface, ConfigType

ccRestorationModel: BaseModelInterface = AutoModel.from_pretrained(
    pretrained_model_name=ConfigType.AnimeSR_v2_4x,
    fp16=False,
    model_dir = 'f:/Hybrid/64bit/ccrestoration_models'
)
clip = ccRestorationModel.inference_video(clip)


clip = core.resize.Bicubic(clip=clip, format=vs.RGBS)
org = core.resize.Bicubic(clip=org, format=vs.RGBS, width=clip.width, height=clip.height)
clip = core.std.Interleave([org.text.Text("Original"), clip.text.Text("Filtered")])
```
I get:
```
Error on frame 1 request:

Traceback (most recent call last):
File "src\\cython\\vapoursynth.pyx", line 3216, in vapoursynth.publicFunction
File "src\\cython\\vapoursynth.pyx", line 3218, in vapoursynth.publicFunction
File "src\\cython\\vapoursynth.pyx", line 834, in vapoursynth.FuncData.__call__
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\vs\vsr.py", line 62, in _inference
output = inference(img)
^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\vsr_base_model.py", line 26, in inference
return tile_vsr(
^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\model\tile.py", line 179, in tile_vsr
output_tile = model(input_tile)
^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\msrswvsr_arch.py", line 57, in forward
out, state = self.cell(torch.cat((x[:, i], x[:, i], x[:, i + 1]), dim=1), out, state)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\msrswvsr_arch.py", line 37, in cell
out = self.recurrent_cell(inp)
^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\ccrestoration\arch\msrswvsr_arch.py", line 118, in forward
x_s1 = self.conv_s1_first(x)
^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\container.py", line 250, in forward
input = module(input)
^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
return self._call_impl(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\conv.py", line 554, in forward
return self._conv_forward(input, self.weight, self.bias)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\Hybrid\64bit\Vapoursynth\Lib\site-packages\torch\nn\modules\conv.py", line 549, in _conv_forward
return F.conv2d(
^^^^^^^^^
RuntimeError: Input type (struct c10::Half) and bias type (float) should be the same
```
But it works If I explicitly set fp16=True.
=> if fp16 isn't explicitly set, could you adjust the code to use fp16=True if the source is RGBH and fp16=false if the source is RGBS ?

**Comment by Tohrusky** [comment]
```
# adjusting color space from YUV420P8 to RGBS for ccrestoration fp32 mode
clip = core.resize.Bicubic(clip=clip, format=vs.RGBS, matrix_in_s="470bg", range_s="limited")
```

No, it should be specified explicitly, as `fp16` may report errors or inference failed in some cases at runtime and may behave differently under different `torch.device`

**Comment by Tohrusky** [comment]
```python
AutoModel.from_pretrained(
    pretrained_model_name=ConfigType.AnimeSR_v2_4x,
    # fp16=clip.format == vs.RGBH, # Pseudocode
    model_dir = 'f:/Hybrid/64bit/ccrestoration_models'
)
```

**Comment by Selur** [comment]
yes, `fp16=clip.format.id == vs.RGBH` does work as expected.
